### ISSUE TITLE
Latest Stable Version of API Specification not Available

### ISSUE THREAD

**Issue by jwwicks** [blend/blend-api-specs#15]
As a Developer I would like for the latest stable version(v5.2.0) of the Blend API as defined in the documentation to be available in the repository so that I can import the spec to tools such as PostMan for testing.

Last listed file is 5.1.0
https://github.com/blend/blend-api-specs/tree/master/version_5

ref: https://developers.blend.com/blend

**Comment by pkat** [comment]
+1. It would be great if the blend-api-specs could be updated with the latest API version.

**Comment by jwwicks** [comment]
Latest Spec updated in Nov. Closing this.
